Upgrade VkNet to 1.75.0
vknet/VkNet.Extensions.Polling pull request #2
Opened 2023-07-11 17:44 UTC by xiadosw

2023-07-14 08:16 UTC, inyutin-maxim requested changes

2023-07-14 08:16 UTC, inyutin-maxim commented on examples/VkNet.Extensions.Polling.Example/VkNet.Extensions.Polling.Example.csproj
> +        <TargetFramework>net6.0</TargetFramework>
С чем связан такой даунгрейд? если тебе нужен именно 6-й то нужно сделать мультитаргетинг

2023-07-14 08:16 UTC, inyutin-maxim commented on build/VkNet.Extensions.Polling.Build.csproj
> +    <TargetFramework>net6.0</TargetFramework>
С чем связан такой даунгрейд? если тебе нужен именно 6-й то нужно сделать мультитаргетинг

2023-07-15 21:32 UTC, xiadosw commented on examples/VkNet.Extensions.Polling.Example/VkNet.Extensions.Polling.Example.csproj
> +        <TargetFramework>net6.0</TargetFramework>
> С чем связан такой даунгрейд? если тебе нужен именно 6-й то нужно сделать мультитаргетинг

Апгрейд. Изначально стоял уже неподдерживаемый .net 5

2023-07-18 19:56 UTC, inyutin-maxim requested changes

2023-07-18 19:56 UTC, inyutin-maxim commented on src/VkNet.Extensions.Polling/LongPollBase.cs
> +                throw new NotSupportedException("Selected type of long poll is not available for this account");
Я не уверен что имеет смысла для русскоязычной соцсети бросать исключения на английском, тк пользователи данного АПИ скорее всего тоже будут в 99% русскоязычными. А если упарываться то надо делать пакеты локализаций

2023-07-18 19:56 UTC, inyutin-maxim commented on src/VkNet.Extensions.Polling/UserLongPoll.cs
> +                            "Failed to get Pts. Problem getting server information")),
Я не уверен что имеет смысла для русскоязычной соцсети бросать исключения на английском, тк пользователи данного АПИ скорее всего тоже будут в 99% русскоязычными. А если упарываться то надо делать пакеты локализаций

2023-07-19 07:54 UTC, inyutin-maxim approved these changes

2023-07-19 07:55 UTC, merged